const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');

async function test() {
  const elements = new Map();
  let saved, failSave = false;
  const document = {getElementById(id) {
    if (!elements.has(id)) elements.set(id, {innerHTML: '', textContent: '', hidden: true});
    return elements.get(id);
  }};
  const record = {async set(data) {if (failSave) throw Error('offline'); saved = structuredClone(data);}};
  const db = {collection: () => ({doc: () => ({collection: () => ({doc: () => record})})})};
  const firestore = Object.assign(() => db, {FieldValue: {serverTimestamp: () => 'timestamp'}});
  const context = vm.createContext({document, firebase: {initializeApp() {}, auth: () => ({onAuthStateChanged() {}}), firestore}, lucide: {createIcons() {}}, window: {scrollTo() {}}, console: {error() {}}});
  const html = fs.readFileSync(path.join(__dirname, '../historia-universal-capitulo-01.html'), 'utf8');
  for (const m of html.matchAll(/<script>([\s\S]*?)<\/script>/g)) vm.runInContext(m[1], context);
  const run = code => vm.runInContext(code, context);
  run("user={uid:'student'};norm();render()");
  assert.match(document.getElementById('app').innerHTML, /¿Cómo quieres estudiar\?/);
  await run("chooseMode('progressive')");
  assert.equal(run("status(4)"), 'locked');
  await run('go(4)');
  assert.equal(run('cur'), 0);
  await run("chooseMode('free');");
  assert.equal(run("side().includes('disabled')"), false);
  assert.equal(run("side().includes('🔒')"), false);
  await run('go(4)');
  assert.equal(saved.currentItem, 4);
  assert.equal(saved.studyMode, 'free');
  await run('selected={0:0,1:0};check(4)');
  assert.equal(saved.percent, 20);
  assert.equal(saved.unlockedItem, 0, 'Passing the last topic must not bypass earlier topics');
  await run("chooseMode('progressive')");
  assert.equal(run('cur'), 0);
  assert.equal(run('P.completedItems.includes(4)'), true);
  assert.equal(run("status(3)"), 'locked');
  await run('selected={0:0,1:0};check(0)');
  assert.equal(run('cur'), 1);
  assert.equal(saved.unlockedItem, 1);
  await run("chooseMode('free');");
  await run('go(3)');
  await run('selected={0:1,1:1};check(3)');
  assert.match(document.getElementById('fb').innerHTML, /seguir explorando/);
  await run('go(2)');
  assert.equal(run('cur'), 2);
  const before = JSON.stringify(saved.completedItems);
  context.reloadData = saved;
  run('norm(reloadData)');
  assert.equal(run('P.studyMode'), 'free');
  assert.equal(run('cur'), 2);
  assert.equal(JSON.stringify(saved.completedItems), before);
  failSave = true;
  await run('go(3)');
  assert.equal(run('cur'), 3, 'Offline saving must not block reading');
  assert.match(document.getElementById('save-status').textContent, /No se pudo guardar/);
  failSave = false;
  await run('persist()');
  assert.equal(document.getElementById('save-status').textContent, '');
  run('norm({completedItems:[0,1,2,3,4],studyMode:"progressive"})');
  assert.equal(run('P.percent'), 100);
  assert.equal(run('canOpen(4)'), true);
  console.log('PASS: mode selection, locks, free navigation, scores, switching, persistence and offline saving');
}
test().catch(error => {console.error(error); process.exitCode = 1;});
